### ISSUE TITLE
XML and JSON that kills EditBone after opening

### ISSUE THREAD

**Issue by piker00** [bonecode/EditBone#182]
[Kill.EBone.zip](https://github.com/bonecode/EditBone/files/517436/Kill.EBone.zip)
JSON that do the same ..\EditBone64\Colors\Default.json

**Comment by bonecode** [comment]
How? I don't notice anything. Maybe I have fixed something that is not in the latest release.

**Comment by piker00** [comment]
Every thing works fine under clean Win10 where EditBone was newer run before.
But under Win7 x64 where I usually run EditBone this bug still present even in 12.6.6  
Actually bug looks like infinite Freeze. 
Also there is other bugs with painting, and little freezes that I didn't report.

**Comment by bonecode** [comment]
That sounds strange. I will download a virtual machine (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and test this.

**Comment by bonecode** [comment]
Could not find it. Any change that you could debug the project on that Windows 7 64-bit machine? 

Btw. Does this happen on 64-bit demo?

**Comment by piker00** [comment]
If you need win7 any edition check this magnet link wit utorrent `magnet:?xt=urn:btih:09c6346055c7da27d0c27736711bf77c73ca8eed&tr=http%3A%2F%2Fbt.nnm-club.info%3A2710%2F00974779dd6c7246f97dfed4a2e0fc76%2Fannounce`

I checked EditBone32 and it has same problem, but late I got message from it: "out of memory"
So it happens with both editions of EditBone.

Later I'll try to check this on an other PC with win7 x64 and Win8.

Finally I'll try to debug project, but it takes time, that pc has no IDE.

**Comment by piker00** [comment]
Ahaaa, i found problem.
It was caused by settings files that stored in C:\Users\{$username}\AppData\Local\EditBone
After deletion of them everything works.

Here in attach my old settings files, that caused problems:
[EditBone.old.Settings.zip](https://github.com/bonecode/EditBone/files/518100/EditBone.old.Settings.zip)

**Comment by bonecode** [comment]
Ok, thanks again. I will investigate what settings could cause this. I remember that I got this also a long time ago.

**Comment by bonecode** [comment]
You could try to set the following options in INI file:

ShowSearchMap=False
WordWrapEnabled=False

There wasn't any other difference. But I found a painting bug with non-fixed width font...

**Comment by piker00** [comment]
And yes it's caused by WordWrapEnabled=True, switching it to false solves the problem.
